### ISSUE TITLE
[Replatform] incremental build don't seem to work properly

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma-website#1069]
### What happened?

If I do a change in `app/_data/docs_nav_kuma_dev.yml` doing `make build` doesn't update the sidebar, I need to do `make clean` first.

**Comment by fabianrbz** [comment]
@lahabana thanks for opening the issue ❤️ .

Unfortunately, that's how the `incremental` flag works :/. You can read more about it [here](https://jekyllrb.com/docs/configuration/incremental-regeneration/), tldr: it only tracks changes to documents or pages or to one of their dependencies - `{% includes %}` -.

However, you can force Jekyll to regenerate a page by adding `regenerate: true` to its frontmatter.
Another option is to remove the [incremental](https://github.com/kumahq/kuma-website/blob/master/jekyll-dev.yml#L11) flag entirely and it will pick up the changes every time. However, bear in mind that it takes ~25 seconds to build the whole site. There are some performance improvements that we would like to implement in order to reduce the build time, but we will tackle those after the release.

**Comment by slonka** [comment]
Can't check this because I can't run the website locally :/ I'm assuming this is still the case.

**Comment by slonka** [comment]
Was able to finally run the website. It seems that it has speed up, it's only 2.2 s

![image](https://github.com/kumahq/kuma-website/assets/2753650/8e1e9dd2-6f7c-4c7e-9452-39e7bbe3d3e5)

maybe we can do `regenerate: true` now?

**Comment by lahabana** [comment]
Still needs clean to update sidebars. There's no easy way out so let's just close this.
