### ISSUE TITLE
Add "Getting Started" top level menu

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma-website#1331]
### What happened?

- "Kuma in Production" is too high in the list, not clear where to start if you're new to Kuma
- [Deploy Multizone](https://kuma.io/docs/2.2.x/production/cp-deployment/multi-zone/#set-up-the-global-control-plane) is under "Kuma in Production" while it's useful when you're just getting familiar with Kuma

**Comment by lobkovilya** [comment]
@bartsmykla @lukidzi please add other points if I missed anything we discussed

**Comment by cloudjumpercat** [comment]
The plan is to add a Quickstart guide as well as a "Get Started in Kuma" section before the "Kuma in Production" section. We just did the Production section first since the other two sections include several completely new pages that the docs team would need tech/SME help to complete. 

Here's the proposed structure:
<img width="751" alt="Screenshot 2023-05-12 at 1 15 11 PM" src="https://github.com/kumahq/kuma-website/assets/75819066/6484c4e6-8b16-4745-9673-1a9e461462ce">

Maybe adding those two sections before "Kuma in Production" would help solve some of the problems? If so and someone has the time to help out with tech reviews/first drafts of those new pages (the ones in red in the image), I'm happy to help out with getting those added.

**Comment by cloudjumpercat** [comment]
@lobkovilya @bartsmykla @lukidzi One thought I had was I could make a temporary [Getting Started section+page just like this one we have in the Mesh docs](https://docs.konghq.com/mesh/latest/gettingstarted/). That way we at least have something there to direct customers to the steps in the getting started process while I work on the new Quickstart + Get Started with Kuma sections that I outlined in the [previous comment](https://github.com/kumahq/kuma-website/issues/1331#issuecomment-1546116552).

What do you think?

**Comment by cloudjumpercat** [comment]
I'd like to pick this up for the next Mesh/Kuma docs IA rework phase

**Comment by lahabana** [comment]
+1 to getting started with a bunch of links to other parts of the site

**Comment by lahabana** [comment]
This was done!
