### ISSUE TITLE
Tag page is empty

### ISSUE THREAD

**Issue by YuikoTakada** [kumahq/kuma-website#300]
there is a link to Tag page in https://github.com/kumahq/kuma-website/blame/master/docs/docs/0.7.2/policies/traffic-permissions.md#L58 but Tag page https://kuma.io/docs/0.7.2/documentation/tags/ is empty.

**Comment by Bradamant3** [comment]
Docs for versions 0.x.x are moved out of the site build because of issues with updating to current versions on our current framework. Unfortunately, links between pages on GH are not reliable, but the tag documentation is present for this version, at https://github.com/kumahq/kuma-website/blob/docs/release-0.x.x/docs/docs/0.7.2/documentation/dps-and-data-model.md#tags
